### PR TITLE
Relog if execution failed with an exception(not FailedModuleException…

### LINKED ISSUE #113: Arisa doesn't try reconnecting and crashes if bugtracker is down
**Describe the bug**
Arisa doesn't try reconnecting and crashes if bugtracker is down or the connection is refused

It should wait a minute and retry

### PR DESCRIPTION
**Pull request by urielsalis**
…) and more than a minute passed

## Purpose
Fix #113

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt [hunk 1]
```diff
@@ -59,6 +60,14 @@ fun main() {
 
             lastRunFile.writeText("${curRunTime.toEpochMilli()}$failed")
             lastRunTime = curRunTime
+        } else if (lastRelog.plus(1, ChronoUnit.MINUTES).isAfter(Instant.now())) {
```
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt:63]: Maybe it would be better to do that only if the last successful run was more than a minute ago?
There are sometimes hiccups where a run fails, but the next run 10 seconds later succeeds again, without a restart or anything.
