### PR TITLE
Redact access tokens in attachments

### LINKED ISSUE #704: Auto-redact JVM crash reports
## The Problem
JVM crash reports contain privacy sensitive information that causes any bug report with one to be privated immediately.

## Possible Solution
Automate what I've done in https://bugs.mojang.com/browse/MC-229049:
* Parse `hs_err_pid` crashes
* Regex privacy sensitive parts and replace them with `<redacted>`
* Attach redacted crash log with name `redacted_hs_err_pidXXXX.log`
* Delete original crash log

### PR DESCRIPTION
**Pull request by Marcono1234**
## Purpose
Fixes #704

Redact access tokens in attachments (e.g. JVM crash reports) by deleting the original attachment and uploading a redacted version to avoid having to make the issue private. Additionally add a comment to let the user know that their attachment has been redacted.

Open questions:
- [x] Should a (bot/hidden) helper message be used for the comment? If so it would require at least two placeholders: Uploader, new attachment names
Edit: Message is currently hardcoded since only one placeholder is supported at the moment, and message is only relevant for Arisa, but is not useful as helper message.

Open tasks:
- [x] Verify that it works with an actual JVM crash report
- [x] Update documentation
- [x] Test in MCTEST

## Approach
`PrivacyModule` has been adjusted to redact access token references in the form `--accessToken ...` like they appear in JVM crash reports. In theory this could be done in a separate module, though it is closely related to what `PrivacyModule` does and having a separate module do this would be tricky (see #527) and would require that the modules are executed in the correct order.

Redaction logic does not reuse `PrivacyModule` regex patterns because they are known to cause false positives and might also not cover everything, e.g. `braintree:` transaction ID is usually provided together with a order ID. We can reliably match the transaction ID (due to its unambiguous `braintree:` prefix), but matching the order ID is not possible. So in that case merely redacting the transaction ID would not suffice.
Therefore redaction only covers the access token for now.

As a safe guard the redacted attachment content is checked to see if it still contains sensitive data (since redaction does not cover everthing); if this is the case the attachment is not redacted and the issue is made private.

A publicly visible comment is added informing the user that their attachments have been redacted.

## Future work
An error during deletion of the existing attachment or upload of the redacted attachment might not be handled correctly; this can lead to the following unwanted situations:
- deletion of old attachment fails, report is made public even though it still contains sensitive attachment
- upload of new attachment fails, attachment is effectively lost

Maybe in the future we could change `IssueUpdateContext` to group actions done by a single module invocation, and abort execution for that module if one of its actions fails (similar to #720); that should solve the above situations. It would also require removing the logging from the `deleteAttachment` and `addAttachmentFile` helper functions and always throw an exception when the HTTP code indicates a failure, because we cannot be sure if we interpret the error HTTP code the way Jira meant it.

#### Checklist
- [x] Included tests
- [x] Updated documentation in [README](https://github.com/mojira/arisa-kt/blob/master/README.md) and [`docs` folder](https://github.com/mojira/arisa-kt/blob/master/docs)
- [x] Tested in MCTEST-142

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt [hunk 1]
```diff
@@ -119,12 +120,19 @@ object HelperMessageService {
...
     fun getMessageWithBotSignature(project: String, key: String, filledText: String? = null, lang: String = "en") =
-        getMessage(project, listOf(key, "i-am-a-bot"), listOf(filledText), lang)
+        getMessage(project, listOf(key, BOT_SIGNATURE_KEY), listOf(filledText), lang)
 
     fun getMessageWithDupeBotSignature(project: String, key: String, filledText: String? = null, lang: String = "en") =
         getMessage(project, listOf(key, "i-am-a-bot-dupe"), listOf(filledText), lang)
 
+    fun getRawMessageWithBotSignature(rawMessage: String): String {
+        // Note: Project does not matter, message is (currently) the same for all projects
+        val botSignature = getSingleMessage("MC", BOT_SIGNATURE_KEY).getOrElse { "" }
```
Comment (Marcono1234) [inline src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt:132]: Hardcoding the project key here might be a little bit hacky. What do you think?

File: src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt [hunk 2]
```diff
@@ -28,67 +34,202 @@ class PrivacyModule(
...
+                        // Use link for attachments
+                        "\n- [^${sanitizeCommentArg(it)}]"
+                    }
+                    val sanitizedUploaderName = sanitizeCommentArg(uploader)
+                    // Does not use helper message because message will only be used by bot and helper messages
+                    // currently only support one placeholder
+                    issue.addRawBotComment(
+                        "@[~$sanitizedUploaderName], sensitive data has been removed from your " +
+                            "attachment(s) and they have been re-uploaded as:$fileNamesString"
+                    )
```
Comment (Marcono1234) [inline src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt:229]: Message is hardcoded instead of using helper message because:
- It uses two placeholders but helper messages only support one at the moment
- This message is only useful for Arisa, as helper message it does not add that much value since the user would have to format the `$fileNamesString` filltext manually.

**Comment by Marcono1234** [comment]
@violine1101, since you originally proposed this feature, could you please have a look when you have some spare time?

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt [hunk 3]
```diff
@@ -0,0 +1,242 @@
...
+                        // Use link for attachments
+                        "\n- [^${sanitizeCommentArg(it)}]"
+                    }
+                    val sanitizedUploaderName = sanitizeCommentArg(uploader)
+                    // Does not use helper message because message will only be used by bot and helper messages
+                    // currently only support one placeholder
+                    issue.addRawBotComment(
+                        "@[~$sanitizedUploaderName], sensitive data has been removed from your " +
+                            "attachment(s) and they have been re-uploaded as:$fileNamesString"
+                    )
```
Comment (Marcono1234) [inline src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:236]: Message is hardcoded instead of using helper message because:
- It uses two placeholders but helper messages only support one at the moment
- This message is only useful for Arisa, as helper message it does not add that much value since the user would have to format the `$fileNamesString` filltext manually.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt [hunk 4]
```diff
@@ -0,0 +1,242 @@
...
+                        // Remove the original attachment
+                        attachment.remove()
+                    }
+                }
+
+                if (fileNames.isNotEmpty()) {
+                    // Use postfix line break to prevent bot signature from appearing as part of last list item
+                    val fileNamesString = fileNames.joinToString(separator = "", postfix = "\n") {
+                        // Use link for attachments
+                        "\n- [^${sanitizeCommentArg(it)}]"
```
Comment (violine1101) [inline src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:228]: The aggressive sanitizing here might lead to some attachment links not working, in case they include unicode characters. Which will, arguably, probably barely ever happen. So not sure if it's a big deal.

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:228]: I guess we run the file names through a regex firstly though, so this isn't an issue.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt [hunk 5]
```diff
@@ -0,0 +1,242 @@
...
+    }
+
+    private data class AttachmentsCheckResult(
+        /** Whether any of the attachments contains sensitive data which cannot be redacted */
+        val attachmentContainsSensitiveData: Boolean,
+        val attachmentsToRedact: List<RedactedAttachment>
+    )
+
+    private fun Issue.checkAttachments(lastRun: Instant): AttachmentsCheckResult {
+        var attachmentContainsSensitiveData: Boolean
```
Comment (violine1101) [inline src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:86]: I feel like the name of this variable is not very good, I got quite confused reading this.

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:86]: Maybe something like `sensitiveDataFound`?

I guess the thing that confused me most is that this variable is not about a particular attachment, but rather about if _any_ attachment contains _any_ sensitive data.

**Review by violine1101 — COMMENTED** [review]
This looks great! Thanks for working on this!

Apart from a few comments, most of which aren't really actionable, I think this should be good to go.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+                assertNotEmpty(attachmentsToRedact),
+                assertTrue(issueContainsSensitiveData),
+                assertNotEmpty(restrictCommentActions)
+            ).bind()
+
+            // Always try to redact attachments, even if issue would be made private anyways
+            // So in case issue was made private erroneously it can easily be made public
+            val redactedAll = redactAttachments(issue, attachmentsToRedact)
+
+            if (!redactedAll || issueContainsSensitiveData) {
```
[the remark this answers is not in the document]
Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:55]: I guess I got confused by the variable naming... it's talking about all attachments containing sensitive data, not all attachments of the ticket.

I guess a more proper variable naming might be `redactingFailed` or something similar (for the negation).

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt [hunk 7]
```diff
@@ -39,19 +39,20 @@ import net.rcarz.jiraclient.Project as JiraProject
 import net.rcarz.jiraclient.User as JiraUser
 import net.rcarz.jiraclient.Version as JiraVersion
 
-fun JiraAttachment.toDomain(jiraClient: JiraClient, issue: JiraIssue) = Attachment(
+fun JiraAttachment.toDomain(jiraClient: JiraClient, issue: JiraIssue, config: Config) = Attachment(
```
[the remark this answers is not in the document]
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:42]: Maybe we could also in the future remove more hardcoded values (e.g. Mojira user group names) and add them to the config. Then we could benefit from the config being available here as well.
But you are right, it is a bit annoying that the config has to be passed around to so much functions.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt (hunk 4 above)
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:228]: We can make `sanitizeCommentArg` more lenient (e.g. by allowing certain character categories) in the future if this turns out to be a problem.

> I guess we run the file names through a regex firstly though

Which one do you mean? We only have a list of regex patterns for names of files which definitely contain sensitive data, but we do not filter malformed file names (except to prevent directory traversal).

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:42]: Something I was thinking is saving the config to a public car somewhere and just calling that statically instead of passing it around

Less functional, but prettier

**Review by urielsalis — DISMISSED** [review]

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:42]: We could also make `Mappers` a class which has `JiraClient` and `Config` as properties, similar to your [`MapFromJira`](https://github.com/mojira/arisa-kt/blob/9a354f3c2e264cc7eb01f3fcb4174921b0ac5b6e/src/main/kotlin/io/github/mojira/arisa/infrastructure/newjira/MapFromJira.kt) class from #720, or my (incomplete) [changes on the `marcono1234/refactor` branch](https://github.com/mojira/arisa-kt/blob/marcono1234/refactor/src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mapper.kt).
This can greatly reduce code duplication.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt (hunk 5 above)
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt]: Changed it to `foundNonRedactableSensitiveData`; a bit verbose but hopefully describes its purpose well enough.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt [hunk 8]
```diff
@@ -99,37 +99,37 @@ class PrivacyModule(
...
-                    if (!attachmentContainsSensitiveData) {
+                    if (!foundNonRedactableSensitiveData) {
                         containsSensitiveData(it.getTextContent())?.let { matchResult ->
-                            attachmentContainsSensitiveData = true
+                            foundNonRedactableSensitiveData = true
                             logFoundSensitiveData("in attachment with ID ${it.id}", matchResult)
                         }
                     }
                     return@mapNotNull null
-                } else {
```
Comment (Marcono1234) [inline src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt]: Changed this from:
```
else {
  if (...) {
    return ...
  }
  return
}
```
to
```
else if (...) {
  return ...
} else {
  return
}
```

These are (except for the variable name change) only indentation changes.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt (hunk 4 above)
Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:232]: From what I can tell, attachments are only scanned if they match the hs_err_pid regex. I might be wrong though.

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt (hunk 8 above)
Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt]: As this is Kotlin and if statements are expressions, in theory you should be able to put the `return` in front of the `if` too, I believe.

Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt]: In theory the `return@mapNotNull` could be removed as well, but at least at the moment I am not convinced by that Kotlin feature yet, at least for larger code blocks as it is the case here. In my opinion that looks too similar to an unused expression (which Kotlin allows, but at least IntelliJ warns about it).

File: src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt (hunk 4 above)
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:232]: It has been some time since I wrote that code, but I don't think there are such requirements. `AccessTokenRedactor` only checks for the file content (more specifically for `--accessToken`), and the `PrivacyModuleTest` passes without specifying any special file names.

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt:232]: Ah yes you're right. That check exists but it doesn't affect the redacting.

**Review by violine1101 — APPROVED** [review]

**Comment by Marcono1234** [comment]
Regarding the "Future work" mentioned in the description: Implementing this might be tricky / not easily possible with the way Jira actions are currently performed. Because `IssueUpdateContext` groups actions by how they are performed against Jira, performing them in the order in which a module executed them is probably difficult without sacrificing efficient grouping of the actions.
