### PR TITLE
Use the normal duplicate comment instead of private if the reporter is the same

### LINKED ISSUE #666: If reporter of a private duplicate is the same as the parent ticket, don't use the private duplicate message
## The Problem
Arisa uses the private duplicate message in this case, however it is incorrect in saying the reporter cannot access the parent ticket in this situation
## Possible Solution
Use the normal duplicate message.

### PR DESCRIPTION
**Pull request by chandler05**
## Purpose
Fix #666
#### Checklist
- [x] Included tests
- [ ] Updated documentation in [README](https://github.com/mojira/arisa-kt/blob/master/README.md) and [wiki](https://github.com/mojira/arisa-kt/wiki)
- [ ] Tested in MCTEST-xxx

### CODE REVIEW

**Review by urielsalis — APPROVED** [review]

File: src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt [hunk 1]
```diff
@@ -94,9 +94,12 @@ class DuplicateMessageModule(
             getField(this[0])
         }
 
-    private fun getPrivateMessageOrNull(issues: List<Issue>): String? {
+    private fun getPrivateMessageOrNull(child: Issue, issues: List<Issue>): String? {
         val parentSecurity = issues.getCommonFieldOrNull { it.securityLevel }
-        return privateMessage.takeIf { parentSecurity != null }
+        val reporters = issues.getCommonFieldOrNull { it.reporter }
+        return privateMessage.takeIf {
+            parentSecurity != null && (reporters == null || child.reporter != reporters)
```
Comment (SPGoding) [inline src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt:101]: Simply `reporters == null` should be enough iirc. The field will be `null` when the reporters on those ticket are not the same.

**Review by SPGoding — APPROVED** [review]
