### PR TITLE
Fix crashing when there's a final newline in lastRun

### LINKED ISSUE #392: Editing with vim/nano adds a new line to the end of last-run, making Arisa crash
## The Bug
Editing with vim/nano adds a new line to the end of last-run, making Arisa crash
## Expected behavior
Remove any blank new lines before processing last-run to allow manual editing

### PR DESCRIPTION
**Pull request by SPGoding**
## Purpose
Fix #392.
#### Checklist
- [ ] Included tests
- [ ] Updated documentation in [README](https://github.com/mojira/arisa-kt/blob/master/README.md) and [wiki](https://github.com/mojira/arisa-kt/wiki)
- [ ] Tested in MCTEST-xxx

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt [hunk 1]
```diff
@@ -124,7 +124,7 @@ private fun readLastRunTime(lastRun: List<String>): Instant {
 
 private fun readLastRun(lastRunFile: File): List<String> {
     return (if (lastRunFile.exists())
-        lastRunFile.readText()
+        lastRunFile.readText().trim()
```
Comment (urielsalis) [inline src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt:127]: IIRC trim removes whitespace but not the last newline, specially as we receive a list of lines

Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt:127]: I believe whitespaces include newlines

Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt:127]: image

Yes, tested in [Kotlin playground](https://play.kotlinlang.org).
