### PR TITLE
Fix tranferring old affected versions

### LINKED ISSUE #229: Don't copy versions older than the oldest version of the duplicated report
## The Problem
TransferVersionsModule currently copies all affected versions to the duplicated report. This can cause problems when a report has a version set as affected despite the bug not being present in that version. If a staff member then fails to notice that (which is not unlikely), that version will be erroneously added to the duplicated report.
This is especially problematic for Bedrock edition due to the incorrect behavior of the FutureVersionModule described in #228. And in general it happens now and then that users just select whatever version is offered, including the latest release, despite a bug not being present there.

## Possible Solution
To prevent these cases it might therefore be good to only copy the affected versions which are newer than the oldest affected version of the duplicated report. This is not completely fool proof because it can happen (as it was the case for 1.8.8) that a release is published after snapshots for the next release have been published. However, this happens rarely and should therefore not be a too big issue.

Example:
1. User creates MC-456, sets 1.15.2 (despite not being affected) and 20w19a
2. Staff member resolves it as duplicate of MC-123 (current affected versions: 20w18a)

Currently Arisa would add 1.15.2 and 20w19a to MC-123, despite 1.15.2 not being affected.
With the proposed change it would only add 20w19a, but not 1.15.2 because it was released before the oldest affected version of the duplicated report (i.e. 20w18a).

### PR DESCRIPTION
**Pull request by SPGoding**
## Purpose
Fix #229.
## Approach
By checking the `releaseDate` of versions.
#### Checklist
- [x] Included tests
- [ ] Tested in MCTEST-xxx

### CODE REVIEW

**Comment by Marcono1234** [comment]
Thanks! Though #229 was only an idea, and there hasn't been much feedback on it yet.
So what do you others think about this change?

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt [hunk 1]
```diff
@@ -61,8 +63,10 @@ fun JiraIssue.getAttachments(remove: (JiraAttachment) -> Either<Throwable, Unit>
     attachments.map { it.toDomain(remove) }
 
 fun JiraVersion.toDomain(execute: (JiraVersion) -> Either<Throwable, Unit>) = Version(
+    name,
     isReleased,
     isArchived,
+    releaseDate.toYearInstant(),
```
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:69]: What's the difference to `toInstance()` (which we usually use here)

File: src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt [hunk 2]
```diff
@@ -229,8 +230,8 @@ class ModuleRegistry(jiraClient: JiraClient, private val config: Config, private
         register(Modules.TransferVersions, TransferVersionsModule()) { issue ->
             AbstractTransferFieldModule.Request(
                 issue.key,
-                issue.getLinks(jiraClient, ::addAffectedVersionById, ::getVersionsGetField),
-                issue.versions.map { it.id }
+                issue.getLinks(jiraClient, ::addAffectedVersionById, ::getVersionsGetField.partially2 { Unit.right() }),
+                issue.getVersions { Unit.right() }
```
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: What's with the hardcoded Unit.right()?

Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: What's with the hardcoded `Unit.right()`?
Is that unfinished code? It's supposed to return a mapped Version, IIRC

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt (hunk 1 above)
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:69]: What's the difference to `toInstance()` (which we usually use for this?

File: src/main/kotlin/io/github/mojira/arisa/domain/Version.kt [hunk 3]
```diff
@@ -1,9 +1,12 @@
 package io.github.mojira.arisa.domain
 
 import arrow.core.Either
+import java.time.Instant
 
 data class Version(
+    val name: String,
```
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/domain/Version.kt:7]: This needs to be kept as ID like before, otherwise the addVersionByID from jira/Calls.kt will not work

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt (hunk 1 above)
Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:69]: The `releaseDate` of version doesn't contain the part after day (it's `yyyy-MM-dd`). I was not sure if the regular one can parse that correctly so I created a new one. Will the regular one work if I replace the code with it?

File: src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt (hunk 2 above)
Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: It's passes as the `execute` function in `domain.Version` which is used to either add or delete the version from issue if I understand correctly. So I hardcoded it as `Unit.right()` here since we don't need either of that functions in this module.

File: src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt (hunk 1 above)
Comment (NeunEinser) [reply src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt:69]: Why wouldn't it?
It's still just an instance of Date.

File: src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt (hunk 2 above)
Comment (NeunEinser) [reply src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: Right, we probably don't even *need* the remove by ID now. I'm cleaning this up a little

Comment (NeunEinser) [reply src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: Okay I understand this now, I am gonna work on #209 now and clean it up there

Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt:234]: Can archived versions be removed? I've heard about that they can only be added but not removed, but I'm not really sure if that's true or not. If we _can_ remove them, #157 might need the remove by ID function.

**Comment by SPGoding** [comment]
(not sure where to put this so I just leave it here since this was first mentioned under this PR)

> Right, we probably don't even need the remove by ID now.

How about removing future versions in the FutureVersion module?

**Comment by NeunEinser** [comment]
It gets mapped to add here: 
https://github.com/mojira/arisa-kt/blob/master/src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt#L201
