### PR TITLE
Dont mark "Unknown" as modded

### LINKED ISSUE #34: Server crash reports are erroneously considered modded
It appears Arisa incorrectly considers all server crash reports erroneously as modded.
Dedicated servers have the value:
```
Is Modded: Unknown (can't tell)
```

Example:
https://bugs.mojang.com/browse/MC-177440

Incorrect code:
https://github.com/mojira/arisa-kt/blob/9cce384da44760e3aed55b31183f37aea04546dc/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L109-L110

### PR DESCRIPTION
**Pull request by urielsalis**
Fixes #34 and #35

### CODE REVIEW

File: src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt [hunk 1]
```diff
@@ -29,6 +29,19 @@ const val EXAMPLE_CRASH = "---- Minecraft Crash Report ----\n" +
...
+        "\n" +
+        "Time: 6/28/17 11:44 AM\n" +
+        "Description: Initializing game\n" +
+        "\n" +
+        "org.lwjgl.LWJGLException: Pixel format not accelerated\n" +
+        "-- System Details --\n" +
+        "Details:\n" +
+        "\tMinecraft Version: 1.8.9\n" +
+        "\tJava Version: 1.8.0_131, Oracle Corporation\n" +
+        "Is Modded: Unknown\n"
```
Comment (Pokechu22) [inline src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:43]: It'd probably be better to use a message from an actual server (you're not going to get an LWJGL crash on a server, for instance, and the actual "Is Modded" value isn't the exact string `Unknown`).  [MC-131071](https://bugs.mojang.com/browse/MC-131071) has some server crashes, and I'm sure there are other ones that can be used (possibly from the watchdog)

Comment (urielsalis) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:43]: I tested https://bugs.mojang.com/secure/attachment/178719/crash-2018-08-02_12.46.39-server.txt but they are quite big to hardcode into the test, got any suggestion?

Comment (Pokechu22) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:43]: I think just this would be good (possibly even dropping the JVM flags, memory, profiler, and player parts), from [this report](https://bugs.mojang.com/secure/attachment/169864/crash-2018-06-05_21.20.43-server.txt):

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 6/5/18 9:20 PM
Description: Exception generating new chunk

java.util.concurrent.ExecutionException: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -174 8

-- System Details --
Details:
	Minecraft Version: 1.13-pre1
	Operating System: Linux (amd64) version 4.4.0-98-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 614132352 bytes (585 MB) / 988282880 bytes (942 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 2 total; -Xmx3584M -XX:MaxPermSize=256M
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [so['KawaiiMutton'/351, l='Vanilla', x=8.50, y=72.00, z=121.50]]
	Data Packs: vanilla
	Is Modded: Unknown (can't tell)
	Type: Dedicated Server (map_server.txt)
```

Comment (urielsalis) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:43]: all done

File: src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt [hunk 2]
```diff
@@ -30,17 +30,48 @@ const val EXAMPLE_CRASH = "---- Minecraft Crash Report ----\n" +
...
+        "\tMinecraft Version: 1.13-pre1\n" +
+        "\tOperating System: Linux (amd64) version 4.4.0-98-generic\n" +
+        "\tJava Version: 1.8.0_151, Oracle Corporation\n" +
+        "\tJava VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation\n" +
+        "\tMemory: 614132352 bytes (585 MB) / 988282880 bytes (942 MB) up to 3340763136 bytes (3186 MB)\n" +
+        "\tJVM Flags: 2 total; -Xmx3584M -XX:MaxPermSize=256M\n" +
+        "\tProfiler Position: N/A (disabled)\n" +
+        "\tPlayer Count: 1 / 20; [so['CENSORED'/351, l='Vanilla', x=8.50, y=72.00, z=121.50]]\n" +
+        "\tData Packs: vanilla\n" +
+        "\tIs Modded: Definitely; Client brand changed to 'fabric'\n" +
```
Comment (Pokechu22) [inline src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:73]: This should probably be <code>Definitely; <ins>Server</ins> brand changed to 'fabric'</code> to cover the dedicated server case.

Comment (NeunEinser) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt:73]: Agreed.

Might also make sense to include one of those Likely, jar signature invalidated ones.
I should be able to dig one of those up tomorrow.

Comment (urielsalis) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt]: Done. Waiting for the signature invalidated ones

Comment (NeunEinser) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt]: Server:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 04.10.19 17:39
Description: Exception ticking world

java.lang.NoSuchFieldError: DO_DAYLIGHT_CYCLE

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1192941208 bytes (1137 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Very likely; Jar signature invalidated
```
Client:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 06.10.19 22:01
Description: Unexpected error

net.minecraft.text.TranslationException: Error while parsing: TranslatableComponent{key='%s updates in tick %2: %s block, %s redstone, %s qc', args=[15031, 4336481, 0, 3347, 11684], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 440810624 bytes (420 MB) / 1142423552 bytes (1089 MB) up to 1890582528 bytes (1803 MB)
	CPUs: 4
	JVM Flags: 0 total; 
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.5.13541 Compatibility Profile Context 24.20.13019.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.13 iRed [Default] v0.02c.zip
	Current Language: English (US)
	CPU: <unknown>
```

One of them should be enough, the is modded value looks the same.

Comment (urielsalis) [reply src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt]: done

File: src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt [hunk 3]
```diff
@@ -107,15 +107,13 @@ class CrashModule(
...
-                    modded = !it.contains("Probably Not", true)
+                    modded = !it.contains("Probably Not", true) && !it.contains("Unknown", true)
             }
 
             if (minecraftVersion != null && javaVersion != null && lines.size >= 7)
                 CrashInfo(
                     CrashInfoType.MINECRAFT,
                     exception?.trim(),
-                    minecraftVersion!!.trim(),
-                    javaVersion!!.trim(),
```
Comment (NeunEinser) [inline src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: Shouldn't the collection of these values also be removed for #35?
In here, you only removed minecraft and java version from CrashInfo, but they are still collected in local variables in here:
https://github.com/mojira/arisa-kt/blob/067d3e422afcedda1bdd0fef617d54d80d07ae5a/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L96-L111
and here the java version:
https://github.com/mojira/arisa-kt/blob/067d3e422afcedda1bdd0fef617d54d80d07ae5a/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L123-L133

Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: First example is used in line 113

Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: second one is used in line 135

Comment (NeunEinser) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: There is no reason to check for null, when not needing the value, is there?
The null check isn't even there in arisa-js IIRC

Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: If I understand the logic correctly, it doesnt actually return it as a valid crash if it doesnt have that.

In Arisa I remembered that we checked if it was a minecraft or java crash that way

Comment (NeunEinser) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: The check whether it's a minecraft or java crash is here:
https://github.com/mojira/arisa-kt/blob/c1242e91c43c7f019ec33ebde49ecac8bf9a300c/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L95
and here:
https://github.com/mojira/arisa-kt/blob/c1242e91c43c7f019ec33ebde49ecac8bf9a300c/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L122
and checks if one of those constants are contained in the file:
https://github.com/mojira/arisa-kt/blob/c1242e91c43c7f019ec33ebde49ecac8bf9a300c/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L17-L18

The null check was just a sanity check I added which is not present in the original module.

Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:118]: done
