### PR TITLE
Fix re-run the ticket being updated instead of the one trigger the update

### LINKED ISSUE #356: If a transfer module fails, last run saves the parent ticket instead of the ticket where Arisa tried to transfer from
## The Bug
The transfer modules (currently TransferLinks and TransferVersions) work on Duplicated issues and will only see the Duplicate report. So if they fail, the Duplicate they fail on should be saved in last-run to be executed again on the next restart after a potential bug fix.
However, the update of course needs to happen in the parent ticket(s). In the current infrastructure, the modules themselves don't fail but the update fails, and the ticket Arisa tried to update gets stashed in last-run instead because of this.

## Example Ticket
Arisa failed on [MC-180306](https://bugs.mojang.com/browse/MC-180306) (see #355) and last run contained [MC-150820](https://bugs.mojang.com/browse/MC-150820) instead.

## Expected behavior
Save the ticket the module was working on instead of the ticket the update failed on.
This could mean introducing an additional optional parameter to the update context. Since multiple modules can potentially update the same ticket, the context should contain a set of origin tickets, if that solution ends up being implemented.

### PR DESCRIPTION
**Pull request by SPGoding**
# Purpose
Fix #356
#### Checklist
- [ ] Included tests
- [ ] Tested in MCTEST-xxx

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt [hunk 1]
```diff
@@ -103,16 +103,20 @@ class ModuleExecutor(
...
+                }
             }
 
         issueUpdateContextCache.storage
-            .mapValues { applyIssueChanges(it.value) }
-            .filterValues { it.isLeft() }
-            .forEach { entry ->
-                (entry.value as Either.Left).a.exceptions.forEach {
-                    log.error("[UPDATE] [${entry.key}] Failed", it)
+            .mapValues { Pair(it.value.triggeredBy, applyIssueChanges(it.value)) }
```
Comment (urielsalis) [inline src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt:112]: Do we have a test for the cache in the moduleexecutor?

Comment (SPGoding) [reply src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt:112]: We have one for adding failed tickets, however that's for the module response section instead of the issue update section. So afaik we don't have tests for that, though I might miss something.

I was trying to add a test for this but wasn't sure how to do it

**Comment by SPGoding** [comment]
I gave up on testing

**Comment by SPGoding** [comment]
I have no curly braces on that line, waht are you stupid lint talking about

**Comment by NeunEinser** [comment]
Late to the party, but I reviewed and approve :P
