### PR TITLE
Fix #680 - Append deobf to the start instead of the end of attachment name

### LINKED ISSUE #680: Name deobfuscated crash reports with deobfuscated stated at the beginning rather than the end
## The Problem

Currently, it is very hard to distinguish obfuscated crash reports from crash reports Arisa deobfuscated:
grafik

You have to hover over the name to see the "deobfuscated" part of the file name: 
grafik

## Possible Solution

Name the crash report `deobf_<original-name>` instead.

### PR DESCRIPTION
**Pull request by urielsalis**
## Purpose
Fix #680
## Approach
Append deobf at the start
#### Checklist
- [ ] Included tests
- [ ] Updated documentation in [README](https://github.com/mojira/arisa-kt/blob/master/README.md) and [`docs` folder](https://github.com/mojira/arisa-kt/blob/master/docs)
- [ ] Tested in MCTEST-xxx

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt [hunk 1]
```diff
@@ -58,9 +58,7 @@ class CrashModule(
             .filter { it.second != null }
             .filterNot {
                 issue.attachments.any { attachment ->
-                    attachment.name == getDeobfName(it.first) || attachment.name.endsWith(
-                        "deobfuscated.txt"
-                    )
+                    attachment.name == getDeobfName(it.first) || attachment.name.startsWith("deobf_")
```
Comment (violine1101) [inline src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:61]: Not really an issue with this PR, but as I understand it this means that Arisa will only ever deobfuscate one crash report on each ticket? Is that desired?

Comment (urielsalis) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt:61]: It will only deobfuscate it once, we have tickets with more than 1 crash and it deobfuscates all of them

this check makes sure we dont try to deobfuscate a crash that has already been deobfuscated (To not have a infinite loop)

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt]: I'm only talking about the second part here, it checks if there's _any_ attachment which is a deobfuscated crash, hence Arisa can only deobfuscate anything on a ticket once.

We already make sure that we only analyze new crashes in line 33 above. IMO the second part of this check is unnecessary or even a bug.

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt]: Ah, wait, I think I see now what the issue is here. But the implementation is faulty.

We should check whether the attachment starts with `deobf` _outside_ of the lambda inside of inside of it. However perhaps it's more foolproof to check if the uploader is Arisa itself.

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt]: Will open a new PR for this issue. It doesn't really cause too much trouble here.

**Review by violine1101 — APPROVED** [review]

File: src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt (hunk 1 above)
Comment (Marcono1234) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt]: > hence Arisa can only deobfuscate anything on a ticket once

I would see it like this as well, that is probably not desired. `assertContainsNewCrash` should really suffice, but a safeguard checking whether Arisa uploaded the crash would not hurt (to prevent endless loops in case the creation date is incorrect).
Do you want to open a new issue / pull request for this?

Comment (violine1101) [reply src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt]: Was working on this already, here's the new PR: #684
